// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: pkg/proto/monitaization.proto

package monit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_monitaization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_monitaization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_monitaization_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_monitaization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_monitaization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_monitaization_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type VideoRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	VideoID   string `protobuf:"bytes,2,opt,name=VideoID,proto3" json:"VideoID,omitempty"`
	Reason    string `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Views     uint32 `protobuf:"varint,4,opt,name=Views,proto3" json:"Views,omitempty"`
	PaidCoins uint32 `protobuf:"varint,5,opt,name=PaidCoins,proto3" json:"PaidCoins,omitempty"`
}

func (x *VideoRewardRequest) Reset() {
	*x = VideoRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_monitaization_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRewardRequest) ProtoMessage() {}

func (x *VideoRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_monitaization_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRewardRequest.ProtoReflect.Descriptor instead.
func (*VideoRewardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_monitaization_proto_rawDescGZIP(), []int{2}
}

func (x *VideoRewardRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *VideoRewardRequest) GetVideoID() string {
	if x != nil {
		return x.VideoID
	}
	return ""
}

func (x *VideoRewardRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VideoRewardRequest) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *VideoRewardRequest) GetPaidCoins() uint32 {
	if x != nil {
		return x.PaidCoins
	}
	return 0
}

type VideoRewardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *VideoRewardResponse) Reset() {
	*x = VideoRewardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_monitaization_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoRewardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRewardResponse) ProtoMessage() {}

func (x *VideoRewardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_monitaization_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRewardResponse.ProtoReflect.Descriptor instead.
func (*VideoRewardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_monitaization_proto_rawDescGZIP(), []int{3}
}

func (x *VideoRewardResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_pkg_proto_monitaization_proto protoreflect.FileDescriptor

var file_pkg_proto_monitaization_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x61, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a,
	0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a, 0x13, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x61, 0x69, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x50, 0x61, 0x69, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x22, 0x2d, 0x0a, 0x13, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xb8, 0x01, 0x0a, 0x0c, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x0b, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x20, 0x2e, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x54, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x20,
	0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x62, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_monitaization_proto_rawDescOnce sync.Once
	file_pkg_proto_monitaization_proto_rawDescData = file_pkg_proto_monitaization_proto_rawDesc
)

func file_pkg_proto_monitaization_proto_rawDescGZIP() []byte {
	file_pkg_proto_monitaization_proto_rawDescOnce.Do(func() {
		file_pkg_proto_monitaization_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_monitaization_proto_rawDescData)
	})
	return file_pkg_proto_monitaization_proto_rawDescData
}

var file_pkg_proto_monitaization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_monitaization_proto_goTypes = []interface{}{
	(*HealthCheckRequest)(nil),  // 0: monitization.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: monitization.HealthCheckResponse
	(*VideoRewardRequest)(nil),  // 2: monitization.VideoRewardRequest
	(*VideoRewardResponse)(nil), // 3: monitization.VideoRewardResponse
}
var file_pkg_proto_monitaization_proto_depIdxs = []int32{
	0, // 0: monitization.Monitization.HealthCheck:input_type -> monitization.HealthCheckRequest
	2, // 1: monitization.Monitization.VideoReward:input_type -> monitization.VideoRewardRequest
	1, // 2: monitization.Monitization.HealthCheck:output_type -> monitization.HealthCheckResponse
	3, // 3: monitization.Monitization.VideoReward:output_type -> monitization.VideoRewardResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_monitaization_proto_init() }
func file_pkg_proto_monitaization_proto_init() {
	if File_pkg_proto_monitaization_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_monitaization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_monitaization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_monitaization_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_monitaization_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoRewardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_monitaization_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_monitaization_proto_goTypes,
		DependencyIndexes: file_pkg_proto_monitaization_proto_depIdxs,
		MessageInfos:      file_pkg_proto_monitaization_proto_msgTypes,
	}.Build()
	File_pkg_proto_monitaization_proto = out.File
	file_pkg_proto_monitaization_proto_rawDesc = nil
	file_pkg_proto_monitaization_proto_goTypes = nil
	file_pkg_proto_monitaization_proto_depIdxs = nil
}
