// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"videoStreaming/pkg/api"
	"videoStreaming/pkg/api/service"
	"videoStreaming/pkg/client"
	"videoStreaming/pkg/config"
	"videoStreaming/pkg/db"
	"videoStreaming/pkg/respository"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	gormDB, err := db.Initdb(c)
	if err != nil {
		return nil, err
	}
	videoRepo := repository.NewVideoRepo(gormDB)
	videoServiceServer := service.NewVideoServer(videoRepo)
	monitClient, err := client.InitClient(c)
	if err != nil {
		return nil, err
	}
	server, err := api.NewgrpcServe(c, videoServiceServer, monitClient)
	if err != nil {
		return nil, err
	}
	return server, nil
}
