// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: pkg/proto/video.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UploadVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName     string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	AvatarId     string `protobuf:"bytes,2,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Intrest      string `protobuf:"bytes,3,opt,name=intrest,proto3" json:"intrest,omitempty"`
	ThumbnailId  string `protobuf:"bytes,4,opt,name=thumbnailId,proto3" json:"thumbnailId,omitempty"`
	Title        string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Discription  string `protobuf:"bytes,6,opt,name=discription,proto3" json:"discription,omitempty"`
	Filename     string `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	UserId       string `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	Exclusive    bool   `protobuf:"varint,9,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	CoinForWatch uint32 `protobuf:"varint,10,opt,name=coin_for_watch,json=coinForWatch,proto3" json:"coin_for_watch,omitempty"`
	Data         []byte `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UploadVideoRequest) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *UploadVideoRequest) GetIntrest() string {
	if x != nil {
		return x.Intrest
	}
	return ""
}

func (x *UploadVideoRequest) GetThumbnailId() string {
	if x != nil {
		return x.ThumbnailId
	}
	return ""
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetDiscription() string {
	if x != nil {
		return x.Discription
	}
	return ""
}

func (x *UploadVideoRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadVideoRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *UploadVideoRequest) GetCoinForWatch() uint32 {
	if x != nil {
		return x.CoinForWatch
	}
	return 0
}

func (x *UploadVideoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoId string `protobuf:"bytes,3,opt,name=videoId,proto3" json:"videoId,omitempty"`
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{3}
}

func (x *UploadVideoResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UploadVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadVideoResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type StreamVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
}

func (x *StreamVideoRequest) Reset() {
	*x = StreamVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVideoRequest) ProtoMessage() {}

func (x *StreamVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVideoRequest.ProtoReflect.Descriptor instead.
func (*StreamVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{4}
}

func (x *StreamVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type StreamVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoChunk []byte `protobuf:"bytes,1,opt,name=video_chunk,json=videoChunk,proto3" json:"video_chunk,omitempty"`
}

func (x *StreamVideoResponse) Reset() {
	*x = StreamVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVideoResponse) ProtoMessage() {}

func (x *StreamVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVideoResponse.ProtoReflect.Descriptor instead.
func (*StreamVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{5}
}

func (x *StreamVideoResponse) GetVideoChunk() []byte {
	if x != nil {
		return x.VideoChunk
	}
	return nil
}

type FindArchivedVideoByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *FindArchivedVideoByUserIdRequest) Reset() {
	*x = FindArchivedVideoByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindArchivedVideoByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindArchivedVideoByUserIdRequest) ProtoMessage() {}

func (x *FindArchivedVideoByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindArchivedVideoByUserIdRequest.ProtoReflect.Descriptor instead.
func (*FindArchivedVideoByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{6}
}

func (x *FindArchivedVideoByUserIdRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type FetchVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId      string `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AvatarId     string `protobuf:"bytes,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Intrest      string `protobuf:"bytes,4,opt,name=intrest,proto3" json:"intrest,omitempty"`
	ThumbnailId  string `protobuf:"bytes,5,opt,name=thumbnailId,proto3" json:"thumbnailId,omitempty"`
	Title        string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	S3Path       string `protobuf:"bytes,7,opt,name=S3Path,proto3" json:"S3Path,omitempty"`
	Archived     bool   `protobuf:"varint,8,opt,name=archived,proto3" json:"archived,omitempty"`
	Views        uint32 `protobuf:"varint,9,opt,name=views,proto3" json:"views,omitempty"`
	Starred      uint32 `protobuf:"varint,10,opt,name=starred,proto3" json:"starred,omitempty"`
	Discription  string `protobuf:"bytes,11,opt,name=discription,proto3" json:"discription,omitempty"`
	Exclusive    bool   `protobuf:"varint,12,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	CoinForWatch uint32 `protobuf:"varint,13,opt,name=coin_for_watch,json=coinForWatch,proto3" json:"coin_for_watch,omitempty"`
	Blocked      bool   `protobuf:"varint,14,opt,name=blocked,proto3" json:"blocked,omitempty"`
}

func (x *FetchVideo) Reset() {
	*x = FetchVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVideo) ProtoMessage() {}

func (x *FetchVideo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVideo.ProtoReflect.Descriptor instead.
func (*FetchVideo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{7}
}

func (x *FetchVideo) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *FetchVideo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FetchVideo) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *FetchVideo) GetIntrest() string {
	if x != nil {
		return x.Intrest
	}
	return ""
}

func (x *FetchVideo) GetThumbnailId() string {
	if x != nil {
		return x.ThumbnailId
	}
	return ""
}

func (x *FetchVideo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FetchVideo) GetS3Path() string {
	if x != nil {
		return x.S3Path
	}
	return ""
}

func (x *FetchVideo) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *FetchVideo) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *FetchVideo) GetStarred() uint32 {
	if x != nil {
		return x.Starred
	}
	return 0
}

func (x *FetchVideo) GetDiscription() string {
	if x != nil {
		return x.Discription
	}
	return ""
}

func (x *FetchVideo) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *FetchVideo) GetCoinForWatch() uint32 {
	if x != nil {
		return x.CoinForWatch
	}
	return 0
}

func (x *FetchVideo) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type FindArchivedVideoByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*FetchVideo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *FindArchivedVideoByUserIdResponse) Reset() {
	*x = FindArchivedVideoByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindArchivedVideoByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindArchivedVideoByUserIdResponse) ProtoMessage() {}

func (x *FindArchivedVideoByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindArchivedVideoByUserIdResponse.ProtoReflect.Descriptor instead.
func (*FindArchivedVideoByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{8}
}

func (x *FindArchivedVideoByUserIdResponse) GetVideos() []*FetchVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type FindUserVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *FindUserVideoRequest) Reset() {
	*x = FindUserVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserVideoRequest) ProtoMessage() {}

func (x *FindUserVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserVideoRequest.ProtoReflect.Descriptor instead.
func (*FindUserVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{9}
}

func (x *FindUserVideoRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type FindUserVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*FetchVideo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *FindUserVideoResponse) Reset() {
	*x = FindUserVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserVideoResponse) ProtoMessage() {}

func (x *FindUserVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserVideoResponse.ProtoReflect.Descriptor instead.
func (*FindUserVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{10}
}

func (x *FindUserVideoResponse) GetVideos() []*FetchVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type FetchAllVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchAllVideoRequest) Reset() {
	*x = FetchAllVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllVideoRequest) ProtoMessage() {}

func (x *FetchAllVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllVideoRequest.ProtoReflect.Descriptor instead.
func (*FetchAllVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{11}
}

type FetchAllVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*FetchVideo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *FetchAllVideoResponse) Reset() {
	*x = FetchAllVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllVideoResponse) ProtoMessage() {}

func (x *FetchAllVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllVideoResponse.ProtoReflect.Descriptor instead.
func (*FetchAllVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{12}
}

func (x *FetchAllVideoResponse) GetVideos() []*FetchVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type GetVideoByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId  string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetVideoByIdRequest) Reset() {
	*x = GetVideoByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIdRequest) ProtoMessage() {}

func (x *GetVideoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIdRequest.ProtoReflect.Descriptor instead.
func (*GetVideoByIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{13}
}

func (x *GetVideoByIdRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetVideoByIdRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetVideoByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetVideoByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId      string        `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	UserName     string        `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AvatarId     string        `protobuf:"bytes,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Intrest      string        `protobuf:"bytes,4,opt,name=intrest,proto3" json:"intrest,omitempty"`
	ThumbnailId  string        `protobuf:"bytes,5,opt,name=thumbnailId,proto3" json:"thumbnailId,omitempty"`
	Title        string        `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	S3Path       string        `protobuf:"bytes,7,opt,name=S3Path,proto3" json:"S3Path,omitempty"`
	Archived     bool          `protobuf:"varint,8,opt,name=archived,proto3" json:"archived,omitempty"`
	IsStarred    bool          `protobuf:"varint,9,opt,name=isStarred,proto3" json:"isStarred,omitempty"`
	Views        uint32        `protobuf:"varint,10,opt,name=views,proto3" json:"views,omitempty"`
	Discription  string        `protobuf:"bytes,11,opt,name=discription,proto3" json:"discription,omitempty"`
	Exclusive    bool          `protobuf:"varint,12,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	CoinForWatch uint32        `protobuf:"varint,13,opt,name=coin_for_watch,json=coinForWatch,proto3" json:"coin_for_watch,omitempty"`
	Blocked      bool          `protobuf:"varint,14,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Starred      uint32        `protobuf:"varint,15,opt,name=starred,proto3" json:"starred,omitempty"`
	Suggestions  []*Suggestion `protobuf:"bytes,16,rep,name=Suggestions,proto3" json:"Suggestions,omitempty"`
}

func (x *GetVideoByIdResponse) Reset() {
	*x = GetVideoByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIdResponse) ProtoMessage() {}

func (x *GetVideoByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIdResponse.ProtoReflect.Descriptor instead.
func (*GetVideoByIdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{14}
}

func (x *GetVideoByIdResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetVideoByIdResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetVideoByIdResponse) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *GetVideoByIdResponse) GetIntrest() string {
	if x != nil {
		return x.Intrest
	}
	return ""
}

func (x *GetVideoByIdResponse) GetThumbnailId() string {
	if x != nil {
		return x.ThumbnailId
	}
	return ""
}

func (x *GetVideoByIdResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetVideoByIdResponse) GetS3Path() string {
	if x != nil {
		return x.S3Path
	}
	return ""
}

func (x *GetVideoByIdResponse) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *GetVideoByIdResponse) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *GetVideoByIdResponse) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetVideoByIdResponse) GetDiscription() string {
	if x != nil {
		return x.Discription
	}
	return ""
}

func (x *GetVideoByIdResponse) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *GetVideoByIdResponse) GetCoinForWatch() uint32 {
	if x != nil {
		return x.CoinForWatch
	}
	return 0
}

func (x *GetVideoByIdResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *GetVideoByIdResponse) GetStarred() uint32 {
	if x != nil {
		return x.Starred
	}
	return 0
}

func (x *GetVideoByIdResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type ArchiveVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
}

func (x *ArchiveVideoRequest) Reset() {
	*x = ArchiveVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveVideoRequest) ProtoMessage() {}

func (x *ArchiveVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveVideoRequest.ProtoReflect.Descriptor instead.
func (*ArchiveVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{15}
}

func (x *ArchiveVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type ArchiveVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ArchiveVideoResponse) Reset() {
	*x = ArchiveVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveVideoResponse) ProtoMessage() {}

func (x *ArchiveVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveVideoResponse.ProtoReflect.Descriptor instead.
func (*ArchiveVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{16}
}

func (x *ArchiveVideoResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type ToggleStarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId  string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	UserNAme string `protobuf:"bytes,2,opt,name=userNAme,proto3" json:"userNAme,omitempty"`
	Starred  bool   `protobuf:"varint,3,opt,name=starred,proto3" json:"starred,omitempty"`
}

func (x *ToggleStarRequest) Reset() {
	*x = ToggleStarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleStarRequest) ProtoMessage() {}

func (x *ToggleStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleStarRequest.ProtoReflect.Descriptor instead.
func (*ToggleStarRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{17}
}

func (x *ToggleStarRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ToggleStarRequest) GetUserNAme() string {
	if x != nil {
		return x.UserNAme
	}
	return ""
}

func (x *ToggleStarRequest) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

type ToggleStarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ToggleStarResponse) Reset() {
	*x = ToggleStarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleStarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleStarResponse) ProtoMessage() {}

func (x *ToggleStarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleStarResponse.ProtoReflect.Descriptor instead.
func (*ToggleStarResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{18}
}

func (x *ToggleStarResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type BlockVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Block   bool   `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *BlockVideoRequest) Reset() {
	*x = BlockVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockVideoRequest) ProtoMessage() {}

func (x *BlockVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockVideoRequest.ProtoReflect.Descriptor instead.
func (*BlockVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{19}
}

func (x *BlockVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *BlockVideoRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlockVideoRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type BlockVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocked bool `protobuf:"varint,1,opt,name=blocked,proto3" json:"blocked,omitempty"`
}

func (x *BlockVideoResponse) Reset() {
	*x = BlockVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockVideoResponse) ProtoMessage() {}

func (x *BlockVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockVideoResponse.ProtoReflect.Descriptor instead.
func (*BlockVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{20}
}

func (x *BlockVideoResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type ReportedVideos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId      string `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AvatarId     string `protobuf:"bytes,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Intrest      string `protobuf:"bytes,4,opt,name=intrest,proto3" json:"intrest,omitempty"`
	ThumbnailId  string `protobuf:"bytes,5,opt,name=thumbnailId,proto3" json:"thumbnailId,omitempty"`
	Title        string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	S3Path       string `protobuf:"bytes,7,opt,name=S3Path,proto3" json:"S3Path,omitempty"`
	Archived     bool   `protobuf:"varint,8,opt,name=archived,proto3" json:"archived,omitempty"`
	Views        uint32 `protobuf:"varint,9,opt,name=views,proto3" json:"views,omitempty"`
	Starred      uint32 `protobuf:"varint,10,opt,name=starred,proto3" json:"starred,omitempty"`
	Blocked      bool   `protobuf:"varint,11,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Exclisive    bool   `protobuf:"varint,12,opt,name=Exclisive,proto3" json:"Exclisive,omitempty"`
	Coin         uint32 `protobuf:"varint,13,opt,name=coin,proto3" json:"coin,omitempty"`
	Reason       string `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`
	Discription  string `protobuf:"bytes,15,opt,name=discription,proto3" json:"discription,omitempty"`
	Exclusive    bool   `protobuf:"varint,16,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	CoinForWatch uint32 `protobuf:"varint,17,opt,name=coin_for_watch,json=coinForWatch,proto3" json:"coin_for_watch,omitempty"`
}

func (x *ReportedVideos) Reset() {
	*x = ReportedVideos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportedVideos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportedVideos) ProtoMessage() {}

func (x *ReportedVideos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportedVideos.ProtoReflect.Descriptor instead.
func (*ReportedVideos) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{21}
}

func (x *ReportedVideos) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ReportedVideos) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ReportedVideos) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *ReportedVideos) GetIntrest() string {
	if x != nil {
		return x.Intrest
	}
	return ""
}

func (x *ReportedVideos) GetThumbnailId() string {
	if x != nil {
		return x.ThumbnailId
	}
	return ""
}

func (x *ReportedVideos) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReportedVideos) GetS3Path() string {
	if x != nil {
		return x.S3Path
	}
	return ""
}

func (x *ReportedVideos) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *ReportedVideos) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *ReportedVideos) GetStarred() uint32 {
	if x != nil {
		return x.Starred
	}
	return 0
}

func (x *ReportedVideos) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *ReportedVideos) GetExclisive() bool {
	if x != nil {
		return x.Exclisive
	}
	return false
}

func (x *ReportedVideos) GetCoin() uint32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *ReportedVideos) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportedVideos) GetDiscription() string {
	if x != nil {
		return x.Discription
	}
	return ""
}

func (x *ReportedVideos) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *ReportedVideos) GetCoinForWatch() uint32 {
	if x != nil {
		return x.CoinForWatch
	}
	return 0
}

type GetReportedVideosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetReportedVideosRequest) Reset() {
	*x = GetReportedVideosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportedVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportedVideosRequest) ProtoMessage() {}

func (x *GetReportedVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportedVideosRequest.ProtoReflect.Descriptor instead.
func (*GetReportedVideosRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{22}
}

type GetReportedVideosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*ReportedVideos `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *GetReportedVideosResponse) Reset() {
	*x = GetReportedVideosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReportedVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportedVideosResponse) ProtoMessage() {}

func (x *GetReportedVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportedVideosResponse.ProtoReflect.Descriptor instead.
func (*GetReportedVideosResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{23}
}

func (x *GetReportedVideosResponse) GetVideos() []*ReportedVideos {
	if x != nil {
		return x.Videos
	}
	return nil
}

type ReportVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ReportVideoRequest) Reset() {
	*x = ReportVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVideoRequest) ProtoMessage() {}

func (x *ReportVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVideoRequest.ProtoReflect.Descriptor instead.
func (*ReportVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{24}
}

func (x *ReportVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ReportVideoRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReportVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ReportVideoResponse) Reset() {
	*x = ReportVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVideoResponse) ProtoMessage() {}

func (x *ReportVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVideoResponse.ProtoReflect.Descriptor instead.
func (*ReportVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{25}
}

func (x *ReportVideoResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type FetchExclusiveVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchExclusiveVideoRequest) Reset() {
	*x = FetchExclusiveVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchExclusiveVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExclusiveVideoRequest) ProtoMessage() {}

func (x *FetchExclusiveVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExclusiveVideoRequest.ProtoReflect.Descriptor instead.
func (*FetchExclusiveVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{26}
}

type FetchExclusiveVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*FetchVideo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *FetchExclusiveVideoResponse) Reset() {
	*x = FetchExclusiveVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchExclusiveVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExclusiveVideoResponse) ProtoMessage() {}

func (x *FetchExclusiveVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExclusiveVideoResponse.ProtoReflect.Descriptor instead.
func (*FetchExclusiveVideoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{27}
}

func (x *FetchExclusiveVideoResponse) GetVideos() []*FetchVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type Suggestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId      string `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AvatarId     string `protobuf:"bytes,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Intrest      string `protobuf:"bytes,4,opt,name=intrest,proto3" json:"intrest,omitempty"`
	ThumbnailId  string `protobuf:"bytes,5,opt,name=thumbnailId,proto3" json:"thumbnailId,omitempty"`
	Title        string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	S3Path       string `protobuf:"bytes,7,opt,name=S3Path,proto3" json:"S3Path,omitempty"`
	Archived     bool   `protobuf:"varint,8,opt,name=archived,proto3" json:"archived,omitempty"`
	Views        uint32 `protobuf:"varint,9,opt,name=views,proto3" json:"views,omitempty"`
	Starred      uint32 `protobuf:"varint,10,opt,name=starred,proto3" json:"starred,omitempty"`
	Discription  string `protobuf:"bytes,11,opt,name=discription,proto3" json:"discription,omitempty"`
	Exclusive    bool   `protobuf:"varint,12,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	CoinForWatch uint32 `protobuf:"varint,13,opt,name=coin_for_watch,json=coinForWatch,proto3" json:"coin_for_watch,omitempty"`
	Blocked      bool   `protobuf:"varint,14,opt,name=blocked,proto3" json:"blocked,omitempty"`
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{28}
}

func (x *Suggestion) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Suggestion) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Suggestion) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *Suggestion) GetIntrest() string {
	if x != nil {
		return x.Intrest
	}
	return ""
}

func (x *Suggestion) GetThumbnailId() string {
	if x != nil {
		return x.ThumbnailId
	}
	return ""
}

func (x *Suggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Suggestion) GetS3Path() string {
	if x != nil {
		return x.S3Path
	}
	return ""
}

func (x *Suggestion) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Suggestion) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Suggestion) GetStarred() uint32 {
	if x != nil {
		return x.Starred
	}
	return 0
}

func (x *Suggestion) GetDiscription() string {
	if x != nil {
		return x.Discription
	}
	return ""
}

func (x *Suggestion) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *Suggestion) GetCoinForWatch() uint32 {
	if x != nil {
		return x.CoinForWatch
	}
	return 0
}

func (x *Suggestion) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type VideoDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoID string `protobuf:"bytes,1,opt,name=VideoID,proto3" json:"VideoID,omitempty"`
}

func (x *VideoDetailsRequest) Reset() {
	*x = VideoDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDetailsRequest) ProtoMessage() {}

func (x *VideoDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDetailsRequest.ProtoReflect.Descriptor instead.
func (*VideoDetailsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{29}
}

func (x *VideoDetailsRequest) GetVideoID() string {
	if x != nil {
		return x.VideoID
	}
	return ""
}

type VideoDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerID string `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Coins   int32  `protobuf:"varint,2,opt,name=Coins,proto3" json:"Coins,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *VideoDetailsResponse) Reset() {
	*x = VideoDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_video_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDetailsResponse) ProtoMessage() {}

func (x *VideoDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_video_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDetailsResponse.ProtoReflect.Descriptor instead.
func (*VideoDetailsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_video_proto_rawDescGZIP(), []int{30}
}

func (x *VideoDetailsResponse) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *VideoDetailsResponse) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *VideoDetailsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_pkg_proto_video_proto protoreflect.FileDescriptor

var file_pkg_proto_video_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1d, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xcc,
	0x02, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x6e, 0x74, 0x72, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x69, 0x6e, 0x74, 0x72, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68,
	0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x76, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x5f,
	0x77, 0x61, 0x74, 0x63, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x69,
	0x6e, 0x46, 0x6f, 0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a,
	0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x22, 0x2e, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x22, 0x36, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x3e, 0x0a, 0x20, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x94, 0x03, 0x0a, 0x0a, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x74,
	0x72, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x72,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x33, 0x50, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x33, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12,
	0x24, 0x0a, 0x0e, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x77, 0x61, 0x74, 0x63,
	0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x46, 0x6f, 0x72,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22,
	0x4b, 0x0a, 0x21, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22, 0x32, 0x0a, 0x14,
	0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x3f, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x22, 0x16, 0x0a, 0x14, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x15, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x41, 0x6c, 0x6c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22, 0x63, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0xee, 0x03, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e,
	0x74, 0x72, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x74,
	0x72, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x33, 0x50, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x33,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x76, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x66, 0x6f, 0x72,
	0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f,
	0x69, 0x6e, 0x46, 0x6f, 0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x12, 0x30,
	0x0a, 0x0b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x10, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x2f, 0x0a, 0x13, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x22, 0x2e, 0x0a, 0x14, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x63, 0x0a, 0x11, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x41, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x41, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x5b, 0x0a, 0x11, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x22, 0x2e, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x22, 0xe2, 0x03, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x72, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x72, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x33, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x33, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x69, 0x65,
	0x77, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x78, 0x63, 0x6c, 0x69, 0x73,
	0x69, 0x76, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x45, 0x78, 0x63, 0x6c, 0x69,
	0x73, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x46, 0x6f,
	0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x47, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x78, 0x63, 0x6c, 0x75,
	0x73, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x45, 0x0a, 0x1b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69,
	0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22, 0x94, 0x03, 0x0a, 0x0a, 0x53, 0x75, 0x67, 0x67,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x72,
	0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x72, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x33,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x33, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x72, 0x65, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12, 0x24,
	0x0a, 0x0e, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x46, 0x6f, 0x72, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22, 0x2f,
	0x0a, 0x13, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x44, 0x22,
	0x5c, 0x0a, 0x14, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x32, 0xb5, 0x07,
	0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28,
	0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x6a, 0x0a, 0x19,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x43, 0x0a, 0x0c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c,
	0x6c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x41, 0x6c, 0x6c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x6c, 0x6c, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x52, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45,
	0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1e, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x43, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_video_proto_rawDescOnce sync.Once
	file_pkg_proto_video_proto_rawDescData = file_pkg_proto_video_proto_rawDesc
)

func file_pkg_proto_video_proto_rawDescGZIP() []byte {
	file_pkg_proto_video_proto_rawDescOnce.Do(func() {
		file_pkg_proto_video_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_video_proto_rawDescData)
	})
	return file_pkg_proto_video_proto_rawDescData
}

var file_pkg_proto_video_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_pkg_proto_video_proto_goTypes = []interface{}{
	(*Request)(nil),                           // 0: pb.Request
	(*Response)(nil),                          // 1: pb.Response
	(*UploadVideoRequest)(nil),                // 2: pb.UploadVideoRequest
	(*UploadVideoResponse)(nil),               // 3: pb.UploadVideoResponse
	(*StreamVideoRequest)(nil),                // 4: pb.StreamVideoRequest
	(*StreamVideoResponse)(nil),               // 5: pb.StreamVideoResponse
	(*FindArchivedVideoByUserIdRequest)(nil),  // 6: pb.FindArchivedVideoByUserIdRequest
	(*FetchVideo)(nil),                        // 7: pb.FetchVideo
	(*FindArchivedVideoByUserIdResponse)(nil), // 8: pb.FindArchivedVideoByUserIdResponse
	(*FindUserVideoRequest)(nil),              // 9: pb.FindUserVideoRequest
	(*FindUserVideoResponse)(nil),             // 10: pb.FindUserVideoResponse
	(*FetchAllVideoRequest)(nil),              // 11: pb.FetchAllVideoRequest
	(*FetchAllVideoResponse)(nil),             // 12: pb.FetchAllVideoResponse
	(*GetVideoByIdRequest)(nil),               // 13: pb.GetVideoByIdRequest
	(*GetVideoByIdResponse)(nil),              // 14: pb.GetVideoByIdResponse
	(*ArchiveVideoRequest)(nil),               // 15: pb.ArchiveVideoRequest
	(*ArchiveVideoResponse)(nil),              // 16: pb.ArchiveVideoResponse
	(*ToggleStarRequest)(nil),                 // 17: pb.ToggleStarRequest
	(*ToggleStarResponse)(nil),                // 18: pb.ToggleStarResponse
	(*BlockVideoRequest)(nil),                 // 19: pb.BlockVideoRequest
	(*BlockVideoResponse)(nil),                // 20: pb.BlockVideoResponse
	(*ReportedVideos)(nil),                    // 21: pb.ReportedVideos
	(*GetReportedVideosRequest)(nil),          // 22: pb.GetReportedVideosRequest
	(*GetReportedVideosResponse)(nil),         // 23: pb.GetReportedVideosResponse
	(*ReportVideoRequest)(nil),                // 24: pb.ReportVideoRequest
	(*ReportVideoResponse)(nil),               // 25: pb.ReportVideoResponse
	(*FetchExclusiveVideoRequest)(nil),        // 26: pb.FetchExclusiveVideoRequest
	(*FetchExclusiveVideoResponse)(nil),       // 27: pb.FetchExclusiveVideoResponse
	(*Suggestion)(nil),                        // 28: pb.Suggestion
	(*VideoDetailsRequest)(nil),               // 29: pb.VideoDetailsRequest
	(*VideoDetailsResponse)(nil),              // 30: pb.VideoDetailsResponse
}
var file_pkg_proto_video_proto_depIdxs = []int32{
	7,  // 0: pb.FindArchivedVideoByUserIdResponse.videos:type_name -> pb.FetchVideo
	7,  // 1: pb.FindUserVideoResponse.videos:type_name -> pb.FetchVideo
	7,  // 2: pb.FetchAllVideoResponse.videos:type_name -> pb.FetchVideo
	28, // 3: pb.GetVideoByIdResponse.Suggestions:type_name -> pb.Suggestion
	21, // 4: pb.GetReportedVideosResponse.videos:type_name -> pb.ReportedVideos
	7,  // 5: pb.FetchExclusiveVideoResponse.videos:type_name -> pb.FetchVideo
	0,  // 6: pb.VideoService.HealthCheck:input_type -> pb.Request
	2,  // 7: pb.VideoService.UploadVideo:input_type -> pb.UploadVideoRequest
	6,  // 8: pb.VideoService.FindArchivedVideoByUserId:input_type -> pb.FindArchivedVideoByUserIdRequest
	9,  // 9: pb.VideoService.FindUserVideo:input_type -> pb.FindUserVideoRequest
	15, // 10: pb.VideoService.ArchiveVideo:input_type -> pb.ArchiveVideoRequest
	11, // 11: pb.VideoService.FetchAllVideo:input_type -> pb.FetchAllVideoRequest
	13, // 12: pb.VideoService.GetVideoById:input_type -> pb.GetVideoByIdRequest
	17, // 13: pb.VideoService.ToggleStar:input_type -> pb.ToggleStarRequest
	19, // 14: pb.VideoService.BlockVideo:input_type -> pb.BlockVideoRequest
	22, // 15: pb.VideoService.GetReportedVideos:input_type -> pb.GetReportedVideosRequest
	24, // 16: pb.VideoService.ReportVideo:input_type -> pb.ReportVideoRequest
	26, // 17: pb.VideoService.FetchExclusiveVideo:input_type -> pb.FetchExclusiveVideoRequest
	29, // 18: pb.VideoService.VideoDetails:input_type -> pb.VideoDetailsRequest
	1,  // 19: pb.VideoService.HealthCheck:output_type -> pb.Response
	3,  // 20: pb.VideoService.UploadVideo:output_type -> pb.UploadVideoResponse
	8,  // 21: pb.VideoService.FindArchivedVideoByUserId:output_type -> pb.FindArchivedVideoByUserIdResponse
	10, // 22: pb.VideoService.FindUserVideo:output_type -> pb.FindUserVideoResponse
	16, // 23: pb.VideoService.ArchiveVideo:output_type -> pb.ArchiveVideoResponse
	12, // 24: pb.VideoService.FetchAllVideo:output_type -> pb.FetchAllVideoResponse
	14, // 25: pb.VideoService.GetVideoById:output_type -> pb.GetVideoByIdResponse
	18, // 26: pb.VideoService.ToggleStar:output_type -> pb.ToggleStarResponse
	20, // 27: pb.VideoService.BlockVideo:output_type -> pb.BlockVideoResponse
	23, // 28: pb.VideoService.GetReportedVideos:output_type -> pb.GetReportedVideosResponse
	25, // 29: pb.VideoService.ReportVideo:output_type -> pb.ReportVideoResponse
	27, // 30: pb.VideoService.FetchExclusiveVideo:output_type -> pb.FetchExclusiveVideoResponse
	30, // 31: pb.VideoService.VideoDetails:output_type -> pb.VideoDetailsResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_video_proto_init() }
func file_pkg_proto_video_proto_init() {
	if File_pkg_proto_video_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_video_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindArchivedVideoByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindArchivedVideoByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAllVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAllVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleStarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleStarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportedVideos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportedVideosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReportedVideosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchExclusiveVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchExclusiveVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Suggestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_video_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_video_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_video_proto_goTypes,
		DependencyIndexes: file_pkg_proto_video_proto_depIdxs,
		MessageInfos:      file_pkg_proto_video_proto_msgTypes,
	}.Build()
	File_pkg_proto_video_proto = out.File
	file_pkg_proto_video_proto_rawDesc = nil
	file_pkg_proto_video_proto_goTypes = nil
	file_pkg_proto_video_proto_depIdxs = nil
}
